name: Parker Auction Service
title: Parker Auction Service
short_title: Parker Auction Service
description: Serving Northwest Arkansas for over 30 years
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/auctions/:path/"
  projects:
    output: true
    permalink: "/programs/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-feed
  - jekyll-archives